# Generated by Django 4.2.16 on 2024-09-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0002_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesin',
            name='status',
            field=models.CharField(default='standby', max_length=50),
        ),
    ]
