# Generated by Django 4.2.16 on 2024-09-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0003_mesin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
