# Generated by Django 4.2.16 on 2024-09-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0004_alter_downtime_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='actor',
        ),
        migrations.AlterField(
            model_name='downtime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
