# Generated by Django 4.2.16 on 2024-09-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0005_logdowntime_remove_downtime_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeByRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AndonMachineApp.downtime')),
            ],
        ),
        migrations.DeleteModel(
            name='LogDowntime',
        ),
    ]
