# Generated by Django 5.1.1 on 2024-09-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0006_downtimebyrole_delete_logdowntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesin',
            name='no_machine',
            field=models.CharField(max_length=255),
        ),
    ]
