# Generated by Django 5.1.1 on 2024-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndonMachineApp', '0009_rename_downtime_downtimemesin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesin',
            name='status',
            field=models.CharField(default='ready', max_length=50),
        ),
    ]
